### PR TITLE
Additional updates to fix build issues

### LINKED ISSUE #1: Update repo with licensing and complete open source

### LINKED ISSUE #2: Add classes from pds-utils dependency

### PR DESCRIPTION
**Pull request by jordanpadams**
## 🗒️ Summary
Additional updates to fix build issues

## ⚙️ Test Data and/or Report
See GitHub Actions

### CODE REVIEW

**Review by nutjob4life — APPROVED** [review]
```
[INFO] Tests run: 673, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by jordanpadams** [comment]
yay build!

**Comment by al-niessner** [comment]
@jordanpadams 

Is snapshot ready?

**Comment by jordanpadams** [comment]
@al-niessner yes. v2.10.0-SNAPSHOT is live. I just tested building validate and it grabbed it from maven central snapshots

**Pull request merged**
