### PR TITLE
validate 531: table extent vs length

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Computing the extent was incorrect. Include the repetitions as part of the extent for better recursive behavior.

## ⚙️ Test Data and/or Report
One of the following should be included here:
* Reference to regression test included in code (preferred wherever reasonable)
* Attach test data here + outputs of tests

## ♻️ Related Issues
NASA-PDS/validate#531

### CODE REVIEW

**Review by nutjob4life — APPROVED** [review]
Nicely done 🫡

**Review by jordanpadams — CHANGES_REQUESTED** [review]
@al-niessner looks like a few tests are failing:

```
[ERROR] Tests run: 672, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 7.555 s <<< FAILURE! - in TestSuite
[ERROR] testGroupFieldWithRepetitions(gov.nasa.pds.objectAccess.example.TestGroupFieldWithRepetitions)  Time elapsed: 0.031 s  <<< FAILURE!
java.lang.IllegalArgumentException: Field length '2' with offset '3001' exceeds the number of bytes in the record '3001'
	at gov.nasa.pds.objectAccess.example.TestGroupFieldWithRepetitions.testGroupFieldWithRepetitions(TestGroupFieldWithRepetitions.java:53)

[ERROR] testTableDefinition(gov.nasa.pds.objectAccess.table.TableBinaryAdapterTest)  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.AssertionError: expected [12] but found [16]
	at gov.nasa.pds.objectAccess.table.TableBinaryAdapterTest.testTableDefinition(TableBinaryAdapterTest.java:79)

[ERROR] testBinaryTableWriter(gov.nasa.pds.objectAccess.TableWriterTest)  Time elapsed: 0.028 s  <<< FAILURE!
java.lang.IndexOutOfBoundsException
	at gov.nasa.pds.objectAccess.TableWriterTest.testBinaryTableWriter(TableWriterTest.java:181)

[ERROR] testExportBinaryTableToCSV(gov.nasa.pds.objectAccess.TableExporterTest)  Time elapsed: 0.048 s  <<< FAILURE!
java.lang.IllegalArgumentException: Field length '4' with offset '34' exceeds the number of bytes in the record '34'
	at gov.nasa.pds.objectAccess.TableExporterTest.exportToCSV(TableExporterTest.java:196)
	at gov.nasa.pds.objectAccess.TableExporterTest.testExportBinaryTableToCSV(TableExporterTest.java:129)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TableExporterTest.testExportBinaryTableToCSV:129->exportToCSV:196 » IllegalArgument
[ERROR]   TableWriterTest.testBinaryTableWriter:181 » IndexOutOfBounds
[ERROR]   TestGroupFieldWithRepetitions.testGroupFieldWithRepetitions:53 » IllegalArgument
[ERROR]   TableBinaryAdapterTest.testTableDefinition:79 expected [12] but found [16]
[INFO]
[ERROR] Tests run: 672, Failures: 4, Errors: 0, Skipped: 0
```

from looking at `TableBinaryAdapterTest.testTableDefinition`, it looks like this assertion is failing:

```
    field = adapter.getField(4); // field 5, 2nd instance of field4
    assertEquals(field.getName(), "field4");
    assertEquals(field.getOffset(), 12); <<<<<<<<<<<<<<
```

I think your fix for `expandBitField` may have been introduced for handling bit fields (`FieldBit`) offsets? Not sure...

**Comment by al-niessner** [comment]
@jordanpadams 

When the error showed up yesterday, double checked the change made and it is only called in a single function. Not sure why it propagate outward. Will double check these errors are not from same method because did not do that yesterday.

**Comment by al-niessner** [comment]
@jordanpadams 

Yes, that seems to have fixed my table problems in validate as well.

**Comment by al-niessner** [comment]
@jordanpadams @nutjob4life @tloubrieu-jpl 

Fixed and ready for review.

**Review by jordanpadams — APPROVED** [review]

**Pull request merged**
